version: '3'
services:
  db:
    image: wqp_nwis_db
    build:
      context: .
    networks:
      wqp:
        ipv4_address: ${DB_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    container_name: ${DATABASE_ADDRESS}

  liquibase:
    image: wqp_nwis_liquibase
    build:
      context: ./liquibase
    networks:
      wqp:
        ipv4_address: ${LIQUIBASE_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NWIS_WS_STAR_OWNER=${NWIS_WS_STAR_OWNER}
      - NWIS_WS_STAR_OWNER_PASSWORD=${NWIS_WS_STAR_OWNER_PASSWORD}
      - NWIS_WS_STAR_DATABASE_NAME=${NWIS_WS_STAR_DATABASE_NAME}
      - NWIS_WS_STAR_SCHEMA_NAME=${NWIS_WS_STAR_SCHEMA_NAME}
      - EXTERNAL_OWNER=${EXTERNAL_OWNER}
      - EXTERNAL_OWNER_PASSWORD=${EXTERNAL_OWNER_PASSWORD}
      - INTERNAL_OWNER=${INTERNAL_OWNER}
      - INTERNAL_OWNER_PASSWORD=${INTERNAL_OWNER_PASSWORD}
      - DATABASE_ADDRESS=${DATABASE_ADDRESS}

    volumes:
      - ./liquibase/changeLogs:/opt/liquibase/workspace
      - ./liquibase/logs:/opt/liquibase/logs
      - ./liquibase/dbInit:/docker-entrypoint-initdb.d

networks:
  wqp:
    external:
      name: ${LOCAL_NETWORK_NAME}
